const KEY={workers:'ch_workers',projects:'ch_projects',tasks:'ch_tasks',reports:'ch_reports',settings:'ch_settings'};
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
const load=(k,d=[])=>JSON.parse(localStorage.getItem(KEY[k])||JSON.stringify(d)); const save=(k,v)=>localStorage.setItem(KEY[k],JSON.stringify(v));
let workers=load('workers'),projects=load('projects'),tasks=load('tasks'),reports=load('reports'),settings=load('settings',{});
const today=()=>new Date().toISOString().slice(0,10); $('#date').value=today();
function uid(){return crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2)}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function hours(a,b,br=0){if(!a||!b)return 0;let [ah,am]=a.split(':').map(Number),[bh,bm]=b.split(':').map(Number);let m=bh*60+bm-(ah*60+am)-Number(br||0);if(m<0)m+=1440;return Math.max(0,m)/60}
function fmt(n){return n.toLocaleString('es-ES',{minimumFractionDigits:2,maximumFractionDigits:2})}
function renderWorkers(){let active=workers.filter(x=>x.active);$('#worker').innerHTML='<option value="">Selecciona trabajador</option>'+active.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('')}
function renderLines(){let box=$('#lines');if(!box.children.length)addLine();}
function projectOptions(){return projects.filter(x=>x.active).map(x=>`<option value="${x.id}">${esc(x.code)} · ${esc(x.name)}</option>`).join('')}
function taskOptions(pid){let p=projects.find(x=>x.id===pid);let allowed=p?.allowedTaskIds||[];return tasks.filter(x=>x.active&&(allowed.length===0||allowed.includes(x.id))).map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('')}
function addLine(data={}){let div=document.createElement('div');div.className='line';div.innerHTML=`<div class="line-grid"><label>Proyecto<select class="project" required><option value="">Selecciona</option>${projectOptions()}</select></label><label>Tarea<select class="task" required><option value="">Selecciona</option></select></label><label>Entrada<input class="start" type="time" value="${data.start||''}" required></label><label>Salida<input class="end" type="time" value="${data.end||''}" required></label><label>Pausa<input class="break" type="number" min="0" value="${data.break||0}" title="Minutos"></label><button type="button" class="danger remove">×</button></div><label class="notes">Observaciones<textarea class="note" placeholder="Opcional">${esc(data.note||'')}</textarea></label><div class="small lineHours">0,00 h</div>`;$('#lines').appendChild(div);div.querySelector('.project').value=data.projectId||'';updateTask(div);div.querySelector('.task').value=data.taskId||'';div.querySelectorAll('input,select,textarea').forEach(e=>e.addEventListener('input',()=>{updateLine(div);updateTotal()}));div.querySelector('.remove').onclick=()=>{if($('#lines').children.length>1){div.remove();updateTotal()}};updateLine(div)}
function updateTask(line){let pid=line.querySelector('.project').value;line.querySelector('.task').innerHTML='<option value="">Selecciona</option>'+taskOptions(pid);updateLine(line)}
function updateLine(line){let h=hours(line.querySelector('.start').value,line.querySelector('.end').value,line.querySelector('.break').value);line.querySelector('.lineHours').textContent=fmt(h)+' h'}
function updateTotal(){let t=0;$$('.line').forEach(l=>{updateLine(l);t+=hours(l.querySelector('.start').value,l.querySelector('.end').value,l.querySelector('.break').value)});$('#totalHours').textContent=fmt(t)+' h'}
$('#addLine').onclick=()=>addLine();$('#lines').addEventListener('change',e=>{if(e.target.classList.contains('project'))updateTask(e.target.closest('.line'));updateTotal()});
function collect(){let lines=$$('.line').map(l=>({projectId:l.querySelector('.project').value,taskId:l.querySelector('.task').value,start:l.querySelector('.start').value,end:l.querySelector('.end').value,break:Number(l.querySelector('.break').value||0),note:l.querySelector('.note').value}));let total=lines.reduce((s,x)=>s+hours(x.start,x.end,x.break),0);return {id:uid(),date:$('#date').value,workerId:$('#worker').value,lines,totalHours:total,createdAt:new Date().toISOString()}}
function validate(r){if(!r.workerId)return 'Selecciona un trabajador.';if(!r.lines.length)return 'Añade al menos una línea.';for(const l of r.lines){if(!l.projectId||!l.taskId||!l.start||!l.end)return 'Completa proyecto, tarea, entrada y salida en todas las líneas.';if(hours(l.start,l.end,l.break)<=0)return 'Revisa las horas de entrada/salida y la pausa.'}return ''}
$('#reportForm').onsubmit=e=>{e.preventDefault();let r=collect(),err=validate(r);if(err){alert(err);return}reports.unshift(r);save('reports',reports);$('#reportState').textContent='Guardado';renderHistory();alert('Parte guardado correctamente.')};
function reportText(r){let w=workers.find(x=>x.id===r.workerId)?.name||'—';let s=`*PARTE DIARIO – CONTROL HORARIO*\nFecha: ${r.date}\nTrabajador: ${w}\n\n`;r.lines.forEach((l,i)=>{let p=projects.find(x=>x.id===l.projectId),t=tasks.find(x=>x.id===l.taskId);s+=`${i+1}. ${p?.code||''} – ${p?.name||''}\n   Tarea: ${t?.name||''}\n   Horario: ${l.start}–${l.end} | Pausa: ${l.break||0} min | Horas: ${fmt(hours(l.start,l.end,l.break))}\n`;if(l.note)s+=`   Obs.: ${l.note}\n`});return s+`\n*TOTAL: ${fmt(r.totalHours)} h*`}
$('#whatsappBtn').onclick=()=>{let r=collect(),err=validate(r);if(err){alert(err);return}let phone=(settings.whatsappPhone||'').replace(/\D/g,'');let url='https://wa.me/'+(phone||'')+'?text='+encodeURIComponent(reportText(r));window.open(url,'_blank')};
function renderHistory(){let box=$('#history');if(!reports.length){box.innerHTML='<div class="empty">Todavía no hay partes guardados.</div>';return}box.innerHTML=reports.map(r=>{let w=workers.find(x=>x.id===r.workerId)?.name||'Trabajador eliminado';let lines=r.lines.map(l=>{let p=projects.find(x=>x.id===l.projectId),t=tasks.find(x=>x.id===l.taskId);return `<div>• ${esc(p?.code||'')} ${esc(p?.name||'')} — ${esc(t?.name||'')} · ${l.start}-${l.end} · ${fmt(hours(l.start,l.end,l.break))} h</div>`}).join('');return `<article class="history-item"><strong>${esc(r.date)} · ${esc(w)}</strong><div class="history-meta">Total: ${fmt(r.totalHours)} h</div><div class="history-lines">${lines}</div></article>`}).join('')}
function csvCell(v){return '"'+String(v??'').replace(/"/g,'""')+'"'}
$('#exportBtn').onclick=()=>{let rows=[['Fecha','Trabajador','Proyecto','Código','Tarea','Entrada','Salida','Pausa min','Horas','Observaciones']];reports.forEach(r=>r.lines.forEach(l=>{let w=workers.find(x=>x.id===r.workerId)?.name||'',p=projects.find(x=>x.id===l.projectId)||{},t=tasks.find(x=>x.id===l.taskId)||{};rows.push([r.date,w,p.name,p.code,t.name,l.start,l.end,l.break, hours(l.start,l.end,l.break).toFixed(2),l.note])}));let csv='\ufeff'+rows.map(row=>row.map(csvCell).join(';')).join('\r\n');let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download='control_horario.csv';a.click();URL.revokeObjectURL(a.href)};
function showView(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view===id));if(id==='historyView')renderHistory()}
$$('.nav[data-view]').forEach(n=>n.onclick=()=>showView(n.dataset.view));$('#navAdmin').onclick=()=>openAdmin();$('#adminBtn').onclick=()=>openAdmin();$('#closeAdmin').onclick=()=>showView('homeView');
let adminTab='workers';
async function hash(s){let b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function openAdmin(){if(!settings.pinHash){adminTab='settings';showView('adminView');renderAdmin();return}$('#pinInput').value='';$('#pinError').textContent='';$('#pinModal').classList.remove('hidden');$('#pinInput').focus()}
$('#cancelPin').onclick=()=>$('#pinModal').classList.add('hidden');$('#confirmPin').onclick=async()=>{if(await hash($('#pinInput').value)===settings.pinHash){$('#pinModal').classList.add('hidden');showView('adminView');renderAdmin()}else $('#pinError').textContent='PIN incorrecto.'};
$$('.tab').forEach(t=>t.onclick=()=>{adminTab=t.dataset.tab;$$('.tab').forEach(x=>x.classList.toggle('active',x===t));renderAdmin()});
function renderAdmin(){let c=$('#adminContent');if(adminTab==='workers')return workersAdmin(c);if(adminTab==='projects')return projectsAdmin(c);if(adminTab==='tasks')return tasksAdmin(c);settingsAdmin(c)}
function workersAdmin(c){c.innerHTML=`<div class="card"><div class="section-title"><h2>Trabajadores</h2><button id="newWorker" class="primary">+ Alta</button></div>${workers.length?workers.map(w=>`<div class="admin-row"><div>${esc(w.name)} <span class="badge ${w.active?'':'off'}">${w.active?'Activo':'Inactivo'}</span></div><button class="secondary toggleW" data-id="${w.id}">${w.active?'Desactivar':'Activar'}</button></div>`).join(''):'<div class="empty">Sin trabajadores. El formulario comienza vacío.</div>'}</div>`;$('#newWorker').onclick=()=>{let name=prompt('Nombre del trabajador:');if(name?.trim()){workers.push({id:uid(),name:name.trim(),active:true});save('workers',workers);renderWorkers();renderAdmin()}};$$('.toggleW').forEach(b=>b.onclick=()=>{let w=workers.find(x=>x.id===b.dataset.id);w.active=!w.active;save('workers',workers);renderWorkers();renderAdmin()})}
function projectsAdmin(c){c.innerHTML=`<div class="card"><div class="section-title"><h2>Proyectos</h2><button id="newProject" class="primary">+ Alta</button></div><div class="notice">Numeración automática: IM260001, IM260002… hasta IM260100.</div>${projects.length?projects.map(p=>`<div class="admin-row"><div><strong>${esc(p.code)}</strong> · ${esc(p.name)} <span class="badge ${p.active?'':'off'}">${p.active?'Activo':'Inactivo'}</span></div><button class="secondary toggleP" data-id="${p.id}">${p.active?'Desactivar':'Activar'}</button></div>`).join(''):'<div class="empty">Sin proyectos.</div>'}</div>`;$('#newProject').onclick=()=>{let name=prompt('Nombre del proyecto:');if(!name?.trim())return;let nums=projects.map(p=>Number((p.code||'').replace('IM260',''))).filter(n=>n>0);let n=(Math.max(0,...nums)+1);if(n>100){alert('Se ha alcanzado IM260100.');return}let code='IM260'+String(n).padStart(3,'0');projects.push({id:uid(),code,name:name.trim(),active:true,allowedTaskIds:[]});save('projects',projects);renderAdmin()};$$('.toggleP').forEach(b=>b.onclick=()=>{let p=projects.find(x=>x.id===b.dataset.id);p.active=!p.active;save('projects',projects);renderAdmin()})}
function tasksAdmin(c){c.innerHTML=`<div class="card"><div class="section-title"><h2>Tareas</h2><button id="newTask" class="primary">+ Alta</button></div>${tasks.length?tasks.map(t=>`<div class="admin-row"><div>${esc(t.name)} <span class="badge ${t.active?'':'off'}">${t.active?'Activa':'Inactiva'}</span></div><button class="secondary toggleT" data-id="${t.id}">${t.active?'Desactivar':'Activar'}</button></div>`).join(''):'<div class="empty">Sin tareas.</div>'}</div><div class="card"><h2>Permisos por proyecto</h2>${projects.length?projects.map(p=>`<div class="admin-row" style="display:block"><strong>${esc(p.code)} · ${esc(p.name)}</strong><div class="check-grid">${tasks.map(t=>`<label><input type="checkbox" class="perm" data-p="${p.id}" data-t="${t.id}" ${(p.allowedTaskIds||[]).includes(t.id)?'checked':''}>${esc(t.name)}</label>`).join('')}</div></div>`).join(''):'<div class="empty">Crea proyectos primero.</div>'}</div>`;$('#newTask').onclick=()=>{let name=prompt('Nombre de la tarea:');if(name?.trim()){tasks.push({id:uid(),name:name.trim(),active:true});save('tasks',tasks);renderAdmin()}};$$('.toggleT').forEach(b=>b.onclick=()=>{let t=tasks.find(x=>x.id===b.dataset.id);t.active=!t.active;save('tasks',tasks);renderAdmin()});$$('.perm').forEach(x=>x.onchange=()=>{let p=projects.find(z=>z.id===x.dataset.p);p.allowedTaskIds=p.allowedTaskIds||[];p.allowedTaskIds=x.checked?[...new Set([...p.allowedTaskIds,x.dataset.t])]:p.allowedTaskIds.filter(id=>id!==x.dataset.t);save('projects',projects);renderAdmin()})}
function settingsAdmin(c){c.innerHTML=`<div class="card"><h2>Configuración</h2><label>Teléfono WhatsApp<input id="waPhone" inputmode="tel" placeholder="346XXXXXXXXX" value="${esc(settings.whatsappPhone||'')}"></label><button id="saveSettings" class="primary" style="margin-top:10px">Guardar</button></div><div class="card"><h2>PIN de administración</h2><p class="small">${settings.pinHash?'PIN configurado. Puedes sustituirlo por uno nuevo.':'No hay PIN configurado. Crea uno para proteger Administración.'}</p><input id="newPin" type="password" inputmode="numeric" maxlength="8" placeholder="Nuevo PIN (4–8 dígitos)"><button id="savePin" class="primary" style="margin-top:10px">Guardar PIN</button></div><div class="card"><h2>Copia de seguridad</h2><p class="small">Exporta o restaura todos los datos locales de la aplicación.</p><div class="actions"><button id="backup" class="secondary">Exportar copia</button><label class="secondary" style="cursor:pointer">Importar copia<input id="restore" type="file" accept="application/json" hidden></label></div></div>`;$('#saveSettings').onclick=()=>{settings.whatsappPhone=$('#waPhone').value.trim();save('settings',settings);alert('Configuración guardada.')};$('#savePin').onclick=async()=>{let p=$('#newPin').value.trim();if(!/^\d{4,8}$/.test(p)){alert('El PIN debe tener entre 4 y 8 dígitos.');return}settings.pinHash=await hash(p);save('settings',settings);alert('PIN actualizado.');renderAdmin()};$('#backup').onclick=()=>{let data={workers,projects,tasks,reports,settings,version:'3.2'};let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='control_horario_backup.json';a.click()};$('#restore').onchange=async e=>{let f=e.target.files[0];if(!f)return;try{let d=JSON.parse(await f.text());if(!d||!Array.isArray(d.workers)||!Array.isArray(d.projects)||!Array.isArray(d.tasks)||!Array.isArray(d.reports))throw Error();workers=d.workers;projects=d.projects;tasks=d.tasks;reports=d.reports;settings=d.settings||{};save('workers',workers);save('projects',projects);save('tasks',tasks);save('reports',reports);save('settings',settings);renderWorkers();alert('Copia restaurada correctamente.');renderAdmin()}catch{alert('La copia no tiene un formato válido.')}}}
renderWorkers();renderLines();renderHistory();