(function(){
'use strict';
const C=window.ControlHorarioSupabase;if(!C||!C.configured)return;
const LS={workers:'ch_workers',projects:'ch_projects',tasks:'ch_tasks',reports:'ch_reports',settings:'ch_settings'};
const LOGO='./logo-imasys.svg';
const j=(k,d)=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d))}catch{return d}};const set=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
let session=null,profile=null,syncing=false,lastHash='';
const workerSession=()=>{try{return JSON.parse(localStorage.getItem('ch_worker_session')||'null')}catch{return null}};
const saveWorkerSession=x=>localStorage.setItem('ch_worker_session',JSON.stringify(x));const clearWorkerSession=()=>localStorage.removeItem('ch_worker_session');
function esc(v){return String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]))}
function ui(){if(document.getElementById('cloudPanel'))return document.getElementById('cloudBox');const d=document.createElement('div');d.id='cloudPanel';d.innerHTML='<div id="cloudBox"></div>';document.body.appendChild(d);return d.querySelector('#cloudBox')}
function applyRoleUI(){const role=profile?.role||workerSession()?.role;const admin=role==='admin'||role==='manager';document.querySelectorAll('[data-view="dashboardView"]').forEach(x=>x.style.display=admin?'':'none');const adminNav=document.getElementById('navAdmin');if(adminNav)adminNav.style.display=admin?'':'none';const workerSelect=document.getElementById('worker'),eid=profile?.employee_id||workerSession()?.employee_id;if(role==='worker'&&workerSelect&&eid){const old=[...workerSelect.options].find(o=>o.value===eid);workerSelect.innerHTML='';const o=document.createElement('option');o.value=eid;o.textContent=old?.text||workerSession()?.name||'Mi usuario';workerSelect.appendChild(o);workerSelect.value=eid;workerSelect.disabled=true}const hw=document.getElementById('historyWorker');if(role==='worker'&&hw){hw.innerHTML='<option value="">Mis partes</option>';hw.disabled=true}}
window.applyRoleUI=applyRoleUI;
function logoMarkup(){return '<div class="cloud-login-logo"><img src="'+LOGO+'" alt="IMASYS Innovación"></div>'}
function render(){const b=ui();if(!b)return;const ws=workerSession();if(!session&&!ws){document.getElementById('cloudPanel').classList.remove('connected');b.innerHTML=logoMarkup()+'<div style="text-align:center"><strong style="font-size:17px">Control Horario V3.3</strong><p style="margin:6px 0 10px;color:#6b7280">Acceso trabajador: selecciona tu nombre y utiliza el código personal asignado por el administrador.</p></div><select id="workerLoginName"><option value="">Cargando trabajadores…</option></select><input id="workerLoginPin" type="password" inputmode="numeric" maxlength="6" placeholder="Código personal (6 dígitos)"><button id="workerLogin">Entrar como trabajador</button><hr><details><summary>Acceso administrador</summary><input id="adminLoginEmail" type="email" placeholder="Correo del administrador"><input id="adminLoginPass" type="password" placeholder="Contraseña"><button id="adminLogin">Entrar como administrador</button></details><small id="cloudMsg"></small>';loadCatalog();document.getElementById('workerLogin').onclick=loginWorker;document.getElementById('adminLogin').onclick=loginAdmin;return}document.getElementById('cloudPanel').classList.add('connected');const role=profile?.role||ws?.role;b.innerHTML='<span class="cloud-status">☁ Conectado'+(ws?.name?' · '+esc(ws.name):'')+'</span><button id="cloudSync">Sincronizar</button><button id="cloudOut">Salir</button><small id="cloudMsg"></small>';document.getElementById('cloudSync').onclick=syncNow;document.getElementById('cloudOut').onclick=logout;applyRoleUI()}
function msg(s){const x=document.getElementById('cloudMsg');if(x)x.textContent=s}
async function loadCatalog(){try{const r=await C.client.functions.invoke('worker-api',{body:{action:'catalog'}});if(r.error)throw r.error;const s=document.getElementById('workerLoginName');if(!s)return;const employees=r.data?.employees||[];s.innerHTML='<option value="">Selecciona tu nombre</option>'+employees.map(e=>`<option value="${e.id}">${esc(e.name)}${e.has_account?'':' · Sin acceso'}</option>`).join('')}catch(e){msg(e.message||'No se pudo cargar la lista')}}
async function loginWorker(){try{const employee_id=document.getElementById('workerLoginName')?.value,pin=document.getElementById('workerLoginPin')?.value.trim();if(!employee_id||!/^[0-9]{6}$/.test(pin))throw new Error('Selecciona tu nombre e introduce un código de 6 dígitos.');const r=await C.client.functions.invoke('worker-api',{body:{action:'login',employee_id,pin}});if(r.error||!r.data?.ok)throw new Error(r.data?.error||'Acceso denegado');saveWorkerSession(r.data);sessionStorage.removeItem('ch_cloud_loaded');location.reload()}catch(e){msg(e.message||'No se pudo iniciar sesión')}}
async function loginAdmin(){try{const email=document.getElementById('adminLoginEmail')?.value.trim(),password=document.getElementById('adminLoginPass')?.value;if(!email||!password)throw new Error('Introduce correo y contraseña.');const r=await C.auth.signIn(email,password);if(r.error)throw r.error;session=r.data.session;sessionStorage.removeItem('ch_cloud_loaded');location.reload()}catch(e){msg(e.message||'No se pudo iniciar sesión')}}
async function logout(){try{const ws=workerSession();if(ws?.token)await C.client.functions.invoke('worker-api',{body:{action:'logout',token:ws.token}})}catch{}clearWorkerSession();if(session)await C.auth.signOut();sessionStorage.removeItem('ch_cloud_loaded');location.reload()}
async function loadProfile(){const {data,error}=await C.client.from('profiles').select('id,company_id,employee_id,role,active').eq('id',session.user.id).maybeSingle();if(error)throw error;profile=data}
async function cloudData(){const ws=workerSession();if(ws&&!session){const r=await C.client.functions.invoke('worker-api',{body:{action:'data',token:ws.token}});if(r.error||r.data?.error)throw(r.error||new Error(r.data.error));const d=r.data,allowed={};(d.project_tasks||[]).forEach(x=>(allowed[x.project_id]??=[]).push(x.task_id));set(LS.workers,(d.employees||[]).map(x=>({id:x.id,name:(x.first_name+' '+x.last_name).trim(),active:x.active,code:x.employee_code})));set(LS.projects,(d.projects||[]).map(x=>({id:x.id,code:x.code,name:x.name,active:true,allowedTaskIds:allowed[x.id]||[]})));set(LS.tasks,(d.tasks||[]).map(x=>({id:x.id,name:x.name,active:true})));set(LS.reports,(d.timesheets||[]).map(mapReport));applyRoleUI();return}const company=profile.company_id;const [e,p,t,pt,ts]=await Promise.all([C.client.from('employees').select('*').eq('company_id',company).eq('active',true),C.client.from('projects').select('*').eq('company_id',company).eq('status','active'),C.client.from('tasks').select('*').eq('company_id',company).eq('active',true),C.client.from('project_tasks').select('*').eq('company_id',company).eq('active',true),C.client.from('timesheets').select('*,timesheet_lines(*)').eq('company_id',company).order('work_date',{ascending:false})]);for(const r of[e,p,t,pt,ts])if(r.error)throw r.error;const allowed={};(pt.data||[]).forEach(x=>(allowed[x.project_id]??=[]).push(x.task_id));set(LS.workers,(e.data||[]).map(x=>({id:x.id,name:(x.first_name+' '+x.last_name).trim(),active:x.active,code:x.employee_code})));set(LS.projects,(p.data||[]).map(x=>({id:x.id,code:x.code,name:x.name,active:true,allowedTaskIds:allowed[x.id]||[]})));set(LS.tasks,(t.data||[]).map(x=>({id:x.id,name:x.name,active:true})));set(LS.reports,(ts.data||[]).map(mapReport));applyRoleUI()}
function mapReport(x){return{id:x.id,date:x.work_date,workerId:x.employee_id,lines:(x.timesheet_lines||[]).map(l=>({projectId:l.project_id,taskId:l.task_id,start:l.start_time?.slice(0,5)||'',end:l.end_time?.slice(0,5)||'',break:0,note:l.description||'',hours:Number(l.hours||0)})),totalHours:Number((x.timesheet_lines||[]).reduce((s,l)=>s+Number(l.hours||0),0)),createdAt:x.created_at}}
async function syncNow(){try{await cloudData();sessionStorage.setItem('ch_cloud_loaded','1');location.reload()}catch(e){msg('Error: '+(e.message||e))}}
async function boot(){try{const ws=workerSession();if(ws&&!session){await cloudData();render();return}await loadProfile();if(!profile){render();return}await cloudData();sessionStorage.setItem('ch_cloud_loaded','1');render()}catch(e){render();msg(e.message||'No se pudo cargar la nube')}}
async function init(){const ws=workerSession();if(ws)session=null;else{const r=await C.auth.getSession();session=r?.data?.session||null}render();if(session||ws)await boot()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();