(function(){
'use strict';
const C=window.ControlHorarioSupabase;if(!C||!C.configured)return;
const LS={workers:'ch_workers',projects:'ch_projects',tasks:'ch_tasks',reports:'ch_reports',settings:'ch_settings'};
const j=(k,d)=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d))}catch{return d}};const set=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
let session=null,profile=null,syncing=false,lastHash='';
const workerSession=()=>{try{return JSON.parse(localStorage.getItem('ch_worker_session')||'null')}catch{return null}};
const saveWorkerSession=x=>localStorage.setItem('ch_worker_session',JSON.stringify(x));
const clearWorkerSession=()=>localStorage.removeItem('ch_worker_session');
function esc(v){return String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]))}
function ui(){if(document.getElementById('cloudPanel'))return document.getElementById('cloudBox');const d=document.createElement('div');d.id='cloudPanel';d.style='position:fixed;right:14px;bottom:76px;z-index:9999;max-width:390px';d.innerHTML='<div id="cloudBox" style="background:#fff;border:1px solid #e5e7eb;border-radius:16px;padding:14px;box-shadow:0 10px 30px #0002;font:14px system-ui"></div>';document.body.appendChild(d);return d.querySelector('#cloudBox')}
function applyRoleUI(){const role=profile?.role||workerSession()?.role;const admin=role==='admin';const dashNav=document.querySelector('[data-view="dashboardView"]'),dashView=document.getElementById('dashboardView');if(dashNav)dashNav.style.display=admin?'':'none';if(!admin&&dashView)dashView.classList.remove('active');const adminNav=document.getElementById('navAdmin');if(adminNav)adminNav.style.display=admin?'':'none';const workerSelect=document.getElementById('worker'),eid=profile?.employee_id||workerSession()?.employee_id;if(role==='worker'&&workerSelect&&eid){const old=Array.from(workerSelect.options).find(o=>o.value===eid);workerSelect.innerHTML='';const o=document.createElement('option');o.value=eid;o.textContent=old?.text||workerSession()?.name||'Mi usuario';workerSelect.appendChild(o);workerSelect.value=eid;workerSelect.disabled=true}const hw=document.getElementById('historyWorker');if(role==='worker'&&hw){hw.innerHTML='<option value="">Mis partes</option>';hw.value='';hw.disabled=true}}
function render(){const b=ui();if(!b)return;const ws=workerSession();if(!session&&!ws){b.innerHTML='<strong>☁️ Control Horario V3.3</strong><p style="margin:6px 0 10px;color:#6b7280">Acceso trabajador: selecciona tu nombre y utiliza el código personal asignado por el administrador.</p><select id="workerLoginName" style="width:100%;box-sizing:border-box;margin:3px 0;padding:8px"><option value="">Cargando trabajadores…</option></select><input id="workerLoginPin" type="password" inputmode="numeric" maxlength="6" placeholder="Código personal (6 dígitos)" style="width:100%;box-sizing:border-box;margin:3px 0;padding:8px"><button id="workerLogin" style="margin-top:6px;width:100%">Entrar como trabajador</button><hr style="border:0;border-top:1px solid #e5e7eb;margin:14px 0"><details><summary style="cursor:pointer">Acceso administrador</summary><input id="adminLoginEmail" type="email" placeholder="Correo del administrador" style="width:100%;box-sizing:border-box;margin:8px 0 3px;padding:8px"><input id="adminLoginPass" type="password" placeholder="Contraseña" style="width:100%;box-sizing:border-box;margin:3px 0;padding:8px"><button id="adminLogin" style="margin-top:6px;width:100%">Entrar como administrador</button></details><small id="cloudMsg"></small>';loadCatalog();document.getElementById('workerLogin').onclick=loginWorker;document.getElementById('adminLogin').onclick=loginAdmin;return}const role=profile?.role||ws?.role;b.innerHTML='<strong>☁️ Conectado</strong><div style="margin:5px 0">'+esc(ws?.name||'')+(role?' · '+esc(role):'')+'</div><button id="cloudSync">Sincronizar</button> <button id="cloudOut">Salir</button><small id="cloudMsg"></small>';document.getElementById('cloudSync').onclick=syncNow;document.getElementById('cloudOut').onclick=logout;applyRoleUI()}
function msg(s){const x=document.getElementById('cloudMsg');if(x)x.textContent=s}
async function loadCatalog(){try{const r=await C.client.functions.invoke('worker-api',{body:{action:'catalog'}});if(r.error)throw r.error;const s=document.getElementById('workerLoginName');if(!s)return;s.innerHTML='<option value="">Selecciona tu nombre</option>'+(r.data?.employees||[]).map(e=>`<option value="${e.id}">${esc(e.name)}</option>`).join('')}catch(e){const s=document.getElementById('workerLoginName');if(s)s.innerHTML='<option value="">No se pudo cargar la lista</option>';msg(e.message||'No se pudo cargar la lista')}}
async function loginWorker(){try{const employee_id=document.getElementById('workerLoginName')?.value,pin=document.getElementById('workerLoginPin')?.value.trim();if(!employee_id||!/^[0-9]{6}$/.test(pin))throw new Error('Selecciona tu nombre e introduce un código de 6 dígitos.');msg('Comprobando…');const r=await C.client.functions.invoke('worker-api',{body:{action:'login',employee_id,pin}});if(r.error)throw r.error;if(!r.data?.ok)throw new Error(r.data?.error||'Acceso denegado');saveWorkerSession(r.data);sessionStorage.removeItem('ch_cloud_loaded');location.reload()}catch(e){msg(e.message||'Código incorrecto')}}
async function loginAdmin(){try{const email=document.getElementById('adminLoginEmail')?.value.trim(),password=document.getElementById('adminLoginPass')?.value;if(!email||!password)throw new Error('Introduce el correo y la contraseña del administrador.');msg('Comprobando administrador…');const r=await C.auth.signIn(email,password);if(r.error)throw r.error;session=r.data.session;sessionStorage.removeItem('ch_cloud_loaded');location.reload()}catch(e){msg(e.message||'No se pudo iniciar sesión')}}
async function logout(){try{const ws=workerSession();if(ws?.token)await C.client.functions.invoke('worker-api',{body:{action:'logout',token:ws.token}})}catch{}clearWorkerSession();if(session)await C.auth.signOut();sessionStorage.removeItem('ch_cloud_loaded');location.reload()}
async function loadProfile(){const {data,error}=await C.client.from('profiles').select('id,company_id,employee_id,role,active').eq('id',session.user.id).maybeSingle();if(error)throw error;profile=data}
async function cloudData(){const ws=workerSession();if(ws&&!session){const r=await C.client.functions.invoke('worker-api',{body:{action:'data',token:ws.token}});if(r.error||r.data?.error)throw(r.error||new Error(r.data.error));const d=r.data;const allowed={};(d.project_tasks||[]).forEach(x=>(allowed[x.project_id]??=[]).push(x.task_id));set(LS.workers,(d.employees||[]).map(x=>({id:x.id,name:(x.first_name+' '+x.last_name).trim(),active:x.active,code:x.employee_code,email:x.email,phone:x.phone})));set(LS.projects,(d.projects||[]).map(x=>({id:x.id,code:x.code,name:x.name,description:x.description,active:true,allowedTaskIds:allowed[x.id]||[]})));set(LS.tasks,(d.tasks||[]).map(x=>({id:x.id,name:x.name,description:x.description,active:true})));set(LS.reports,(d.timesheets||[]).map(x=>({id:x.id,date:x.work_date,workerId:x.employee_id,lines:(x.timesheet_lines||[]).map(l=>({projectId:l.project_id,taskId:l.task_id,start:l.start_time?.slice(0,5)||'',end:l.end_time?.slice(0,5)||'',break:0,note:l.description||''})),totalHours:Number((x.timesheet_lines||[]).reduce((s,l)=>s+Number(l.hours||0),0)||0),createdAt:x.created_at})));lastHash=hashLocal();applyRoleUI();return}
 const company=profile.company_id,workerOnly=profile.role==='worker';const [e,p,t,pt,ts]=await Promise.all([C.client.from('employees').select('*').eq('company_id',company).eq('active',true).order('first_name'),C.client.from('projects').select('*').eq('company_id',company).eq('status','active').order('code'),C.client.from('tasks').select('*').eq('company_id',company).eq('active',true).order('name'),C.client.from('project_tasks').select('*').eq('company_id',company).eq('active',true),workerOnly?C.client.from('timesheets').select('*,timesheet_lines(*)').eq('company_id',company).eq('employee_id',profile.employee_id).order('work_date',{ascending:false}):C.client.from('timesheets').select('*,timesheet_lines(*)').eq('company_id',company).order('work_date',{ascending:false})]);for(const r of [e,p,t,pt,ts])if(r.error)throw r.error;const allowed={};pt.data.forEach(x=>(allowed[x.project_id]??=[]).push(x.task_id));set(LS.workers,e.data.map(x=>({id:x.id,name:(x.first_name+' '+x.last_name).trim(),active:x.active,code:x.employee_code,email:x.email,phone:x.phone})));set(LS.projects,p.data.map(x=>({id:x.id,code:x.code,name:x.name,description:x.description,active:true,allowedTaskIds:allowed[x.id]||[]})));set(LS.tasks,t.data.map(x=>({id:x.id,name:x.name,description:x.description,active:true})));set(LS.reports,ts.data.map(x=>({id:x.id,date:x.work_date,workerId:x.employee_id,lines:(x.timesheet_lines||[]).map(l=>({projectId:l.project_id,taskId:l.task_id,start:l.start_time?.slice(0,5)||'',end:l.end_time?.slice(0,5)||'',break:0,note:l.description||''})),totalHours:Number((x.timesheet_lines||[]).reduce((s,l)=>s+Number(l.hours||0),0)||0),createdAt:x.created_at})));lastHash=hashLocal();applyRoleUI()}
function hashLocal(){return [LS.workers,LS.projects,LS.tasks,LS.reports].map(k=>localStorage.getItem(k)||'').join('|')}
function calc(a,b,br){if(!a||!b)return 0;let[ah,am]=a.split(':').map(Number),[bh,bm]=b.split(':').map(Number),m=bh*60+bm-ah*60-am;if(m<0)m+=1440;return Math.max(0,m-Number(br||0))/60}
async function pushLocal(){if(syncing)return;const ws=workerSession();if(ws&&!session){syncing=true;try{const reports=j(LS.reports,[]);for(const r of reports){if(r.workerId!==ws.employee_id)continue;const report={...r,lines:(r.lines||[]).map(l=>({...l,hours:calc(l.start,l.end,l.break)}))};const x=await C.client.functions.invoke('worker-api',{body:{action:'save',token:ws.token,report}});if(x.error||x.data?.error)throw(x.error||new Error(x.data.error))}lastHash=hashLocal();msg('Sincronizado ✓')}catch(e){msg('Error: '+(e.message||e))}finally{syncing=false}return}
 if(!profile||!['admin','manager'].includes(profile.role))return;syncing=true;try{const company=profile.company_id,workers=j(LS.workers,[]),projects=j(LS.projects,[]),tasks=j(LS.tasks,[]),reports=j(LS.reports,[]);for(const w of workers){const parts=String(w.name||'').trim().split(/\s+/);await C.client.from('employees').upsert({id:w.id,company_id:company,employee_code:w.code||w.id.slice(0,8),first_name:parts.shift()||w.name||'Trabajador',last_name:parts.join(' '),email:w.email||null,phone:w.phone||null,active:w.active!==false},{onConflict:'id'})}for(const t of tasks)await C.client.from('tasks').upsert({id:t.id,company_id:company,name:t.name,description:t.description||null,active:t.active!==false},{onConflict:'id'});for(const p of projects){await C.client.from('projects').upsert({id:p.id,company_id:company,code:p.code,name:p.name,description:p.description||null,status:p.active===false?'closed':'active'},{onConflict:'id'});await C.client.from('project_tasks').delete().eq('project_id',p.id);for(const tid of(p.allowedTaskIds||[]))await C.client.from('project_tasks').upsert({company_id:company,project_id:p.id,task_id:tid,active:true},{onConflict:'project_id,task_id'})}for(const r of reports){await C.client.from('timesheets').upsert({id:r.id,company_id:company,employee_id:r.workerId,work_date:r.date,status:'submitted'},{onConflict:'id'});await C.client.from('timesheet_lines').delete().eq('timesheet_id',r.id);for(const l of(r.lines||[]))await C.client.from('timesheet_lines').insert({timesheet_id:r.id,project_id:l.projectId,task_id:l.taskId,start_time:l.start||null,end_time:l.end||null,hours:calc(l.start,l.end,l.break),description:l.note||null})}lastHash=hashLocal();msg('Sincronizado ✓')}catch(e){msg('Error: '+(e.message||e))}finally{syncing=false}}
async function syncNow(){try{await pushLocal();await cloudData();sessionStorage.setItem('ch_cloud_loaded','1');location.reload()}catch(e){msg(e.message||'Error de sincronización')}}
async function boot(){try{const ws=workerSession();if(ws&&!session){await cloudData();render();return}await loadProfile();if(!profile){render();msg('Cuenta sin perfil.');return}if(!sessionStorage.getItem('ch_cloud_loaded')){await cloudData();sessionStorage.setItem('ch_cloud_loaded','1');location.reload();return}render()}catch(e){render();msg(e.message||'No se pudo cargar la nube')}}
async function init(){const ws=workerSession();session=ws?null:await C.auth.getSession();render();if(session||ws)await boot()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
