(function(){
'use strict';
const C=()=>window.ControlHorarioSupabase;let users=[];
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const isAdmin=()=>window.ControlHorarioRole==='admin';
const call=body=>{const c=C();if(!c?.configured||!c.client)throw new Error('Supabase no configurado');return c.client.functions.invoke('admin-users',{body})};
const employees=()=>{try{return JSON.parse(localStorage.getItem('ch_workers')||'[]').filter(x=>x.active!==false)}catch{return []}};
async function load(){const r=await call({action:'list'});if(r.error)throw r.error;users=r.data?.users||[];render()}
function render(){const c=document.getElementById('adminContent');if(!c)return;const em=employees();c.innerHTML=`<div class="card users-card"><div class="section-title"><div><h2>Usuarios y accesos</h2><p class="small">Las cuentas se identifican por teléfono móvil y acceden mediante código SMS.</p></div><button id="newUser" class="primary">＋ Nueva cuenta</button></div><div class="users-table">${users.length?users.map(u=>{const name=u.employee?.name||'Sin trabajador';const status=u.active?'Activa':'Desactivada';const confirm=u.phone_confirmed?'Confirmado':'Pendiente';return `<div class="user-row"><div><strong>📱 ${esc(u.phone||'Sin teléfono')}</strong><div class="small">${esc(name)} · ${esc(u.role||'sin rol')}</div></div><div><span class="badge">${status}</span> <span class="badge">${confirm}</span></div><div class="user-actions"><select class="user-role" data-id="${u.id}" ${u.id===currentId()?'disabled':''}><option value="worker" ${u.role==='worker'?'selected':''}>Trabajador</option><option value="manager" ${u.role==='manager'?'selected':''}>Manager</option><option value="admin" ${u.role==='admin'?'selected':''}>Administrador</option></select><select class="user-employee" data-id="${u.id}" ${u.id===currentId()?'disabled':''}><option value="">Sin trabajador</option>${em.map(e=>`<option value="${e.id}" ${u.employee_id===e.id?'selected':''}>${esc(e.name)}</option>`).join('')}</select><button class="secondary toggle-user" data-id="${u.id}" data-active="${u.active}">${u.active?'Desactivar':'Activar'}</button></div></div>`}).join(''):'<div class="empty">No hay cuentas creadas todavía.</div>'}</div></div>`;
 document.getElementById('newUser').onclick=showCreate;c.querySelectorAll('.toggle-user').forEach(b=>b.onclick=()=>update(b.dataset.id,{active:b.dataset.active!=='true'}));c.querySelectorAll('.user-role').forEach(s=>s.onchange=()=>update(s.dataset.id,{role:s.value}));c.querySelectorAll('.user-employee').forEach(s=>s.onchange=()=>update(s.dataset.id,{employee_id:s.value}))}
function currentId(){return window._chAuthUserId||''}
async function update(id,patch){try{const r=await call({action:'update',user_id:id,...patch});if(r.error)throw r.error;await load()}catch(e){alert(e.message||'No se pudo actualizar la cuenta');await load()}}
function showCreate(){const em=employees(),box=document.createElement('div');box.className='modal';box.innerHTML=`<div class="modal-card"><h2>Nueva cuenta</h2><p class="small">El trabajador accederá con su teléfono y un código de verificación SMS.</p><label>Teléfono móvil<input id="newUserPhone" type="tel" inputmode="tel" autocomplete="tel" placeholder="+34 600 000 000" required></label><label>Trabajador<select id="newUserEmployee"><option value="">Selecciona trabajador</option>${em.map(e=>`<option value="${e.id}">${esc(e.name)}</option>`).join('')}</select></label><label>Rol<select id="newUserRole"><option value="worker">Trabajador</option><option value="manager">Manager</option><option value="admin">Administrador</option></select></label><p id="newUserError" class="error"></p><div class="actions"><button id="cancelNewUser" class="secondary">Cancelar</button><button id="saveNewUser" class="primary">Crear cuenta</button></div></div>`;document.body.appendChild(box);box.querySelector('#cancelNewUser').onclick=()=>box.remove();box.querySelector('#saveNewUser').onclick=async()=>{const phone=box.querySelector('#newUserPhone').value.trim(),employee_id=box.querySelector('#newUserEmployee').value,role=box.querySelector('#newUserRole').value;try{if(!phone||!employee_id)throw new Error('Teléfono y trabajador son obligatorios.');box.querySelector('#saveNewUser').disabled=true;const r=await call({action:'create',phone,employee_id,role});if(r.error)throw r.error;box.remove();alert('Cuenta creada. El trabajador podrá solicitar su código SMS en el móvil.');await load()}catch(e){box.querySelector('#newUserError').textContent=e.message||'No se pudo crear la cuenta';box.querySelector('#saveNewUser').disabled=false}}}
function addTab(){if(!isAdmin())return;const tabs=document.querySelector('.tabs');if(!tabs||tabs.querySelector('[data-tab="users"]'))return;const b=document.createElement('button');b.className='tab';b.dataset.tab='users';b.textContent='Usuarios y accesos';tabs.appendChild(b)}
function open(){if(!isAdmin())return;addTab();document.querySelectorAll('.tabs .tab').forEach(x=>x.classList.remove('active'));document.querySelector('.tabs [data-tab="users"]')?.classList.add('active');load().catch(e=>{const c=document.getElementById('adminContent');if(c)c.innerHTML='<div class="card"><p class="error">'+esc(e.message||e)+'</p></div>'})}
document.addEventListener('click',e=>{const b=e.target.closest('.tabs [data-tab="users"]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();open()},true);
const css=document.createElement('style');css.textContent='.users-table{display:grid;gap:10px}.user-row{display:grid;grid-template-columns:1.4fr .9fr 1.8fr;gap:12px;align-items:center;padding:12px 0;border-top:1px solid #e5e7eb}.user-actions{display:flex;gap:7px;flex-wrap:wrap}.user-actions select{margin:0}.badge{display:inline-block;padding:3px 7px;border-radius:99px;background:#f3f4f6;font-size:11px}.users-card .section-title{align-items:center}@media(max-width:850px){.user-row{grid-template-columns:1fr}.user-actions{justify-content:flex-start}}';document.head.appendChild(css);const timer=setInterval(addTab,800);window.addEventListener('beforeunload',()=>clearInterval(timer));window.ControlHorarioUsers={open,load};
})();
