(function(){
'use strict';
const C=()=>window.ControlHorarioSupabase;let users=[];
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const isAdmin=()=>window.ControlHorarioRole==='admin';
const call=body=>{const c=C();if(!c?.configured||!c.client)throw new Error('Supabase no configurado');return c.client.functions.invoke('admin-users',{body})};
async function load(){const r=await call({action:'list'});if(r.error)throw r.error;users=r.data?.users||[];render()}
function render(){const c=document.getElementById('adminContent');if(!c)return;c.innerHTML=`<div class="card users-card"><div class="section-title"><div><h2>Usuarios y accesos</h2><p class="small">El administrador crea el acceso. El trabajador entra seleccionando su nombre y usando su código personal de 6 dígitos.</p></div><button id="newUser" class="primary">＋ Nueva cuenta</button></div><div class="users-table">${users.length?users.map(u=>{const name=u.employee?.name||'Sin trabajador';const status=u.has_pin?(u.active?'Activa':'Desactivada'):'Sin cuenta';const pin=u.has_pin?'Código asignado':'Sin código';return `<div class="user-row"><div><strong>👤 ${esc(name)}</strong><div class="small">${esc(u.employee?.code||'')} · Trabajador</div></div><div><span class="badge">${status}</span> <span class="badge">${pin}</span></div><div class="user-actions">${u.has_pin?`<button class="secondary pin-user" data-id="${u.employee_id}">Cambiar código</button><button class="secondary toggle-user" data-id="${u.employee_id}" data-active="${u.active}">${u.active?'Desactivar':'Activar'}</button>`:'<button class="secondary create-user" data-id="'+u.employee_id+'">Crear acceso</button>'}</div></div>`}).join(''):'<div class="empty">No hay trabajadores creados todavía.</div>'}</div></div>`;document.getElementById('newUser').onclick=showCreate;c.querySelectorAll('.toggle-user').forEach(b=>b.onclick=()=>update(b.dataset.id,{active:b.dataset.active!=='true'}));c.querySelectorAll('.pin-user').forEach(b=>b.onclick=()=>changePin(b.dataset.id));c.querySelectorAll('.create-user').forEach(b=>b.onclick=()=>createFor(b.dataset.id))}
async function update(employee_id,patch){try{const r=await call({action:'update',employee_id,...patch});if(r.error)throw r.error;await load()}catch(e){alert(e.message||'No se pudo actualizar la cuenta');await load()}}
function pinPrompt(title='Código personal'){const p=prompt(title+' (6 dígitos):');if(p===null)return null;if(!/^\d{6}$/.test(p))throw new Error('El código debe tener exactamente 6 dígitos.');return p}
async function changePin(id){try{const pin=pinPrompt('Nuevo código');if(pin===null)return;await update(id,{pin})}catch(e){alert(e.message||'No se pudo cambiar el código')}}
function localWorkers(){try{return JSON.parse(localStorage.getItem('ch_workers')||'[]').filter(x=>x.active!==false)}catch{return []}}
async function createFor(employee_id,worker){try{const pin=pinPrompt('Código personal');if(pin===null)return;const body={action:'create',employee_id,pin};if(worker)body.employee={id:worker.id,name:worker.name,code:worker.code,email:worker.email,phone:worker.phone,active:worker.active!==false};const r=await call(body);if(r.error)throw r.error;alert('Acceso creado correctamente.');await load()}catch(e){alert(e.message||'No se pudo crear la cuenta')}}
function showCreate(){const em=localWorkers(),existing=new Set(users.map(u=>u.employee_id)),available=em.filter(e=>!existing.has(e.id));const box=document.createElement('div');box.className='modal';box.innerHTML=`<div class="modal-card"><h2>Nueva cuenta</h2><p class="small">Elige un trabajador y asigna un código personal de 6 dígitos.</p><label>Trabajador<select id="newUserEmployee"><option value="">Selecciona trabajador</option>${available.map(e=>`<option value="${e.id}">${esc(e.name)}</option>`).join('')}</select></label><label>Código personal<input id="newUserPin" type="password" inputmode="numeric" maxlength="6" placeholder="6 dígitos"></label><p id="newUserError" class="error"></p><div class="actions"><button id="cancelNewUser" class="secondary">Cancelar</button><button id="saveNewUser" class="primary">Crear cuenta</button></div></div>`;document.body.appendChild(box);box.querySelector('#cancelNewUser').onclick=()=>box.remove();box.querySelector('#saveNewUser').onclick=async()=>{const id=box.querySelector('#newUserEmployee').value,pin=box.querySelector('#newUserPin').value.trim(),worker=em.find(e=>e.id===id);try{if(!id||!/^[0-9]{6}$/.test(pin))throw new Error('Selecciona trabajador e introduce un código de 6 dígitos.');box.querySelector('#saveNewUser').disabled=true;const body={action:'create',employee_id:id,pin,employee:worker?{id:worker.id,name:worker.name,code:worker.code,email:worker.email,phone:worker.phone,active:worker.active!==false}:null};const r=await call(body);if(r.error)throw r.error;box.remove();alert('Cuenta creada correctamente.');await load()}catch(e){box.querySelector('#newUserError').textContent=e.message||'No se pudo crear la cuenta';box.querySelector('#saveNewUser').disabled=false}}}
function addTab(){if(!isAdmin())return;const tabs=document.querySelector('.tabs');if(!tabs||tabs.querySelector('[data-tab="users"]'))return;const b=document.createElement('button');b.className='tab';b.dataset.tab='users';b.textContent='Usuarios y accesos';tabs.appendChild(b)}
function open(){if(!isAdmin())return;addTab();document.querySelectorAll('.tabs .tab').forEach(x=>x.classList.remove('active'));document.querySelector('.tabs [data-tab="users"]')?.classList.add('active');load().catch(e=>{const c=document.getElementById('adminContent');if(c)c.innerHTML='<div class="card"><p class="error">'+esc(e.message||e)+'</p></div>'})}
document.addEventListener('click',e=>{const b=e.target.closest('.tabs [data-tab="users"]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();open()},true);
const css=document.createElement('style');css.textContent='.users-table{display:grid;gap:10px}.user-row{display:grid;grid-template-columns:1.4fr .9fr 1.8fr;gap:12px;align-items:center;padding:12px 0;border-top:1px solid #e5e7eb}.user-actions{display:flex;gap:7px;flex-wrap:wrap}.badge{display:inline-block;padding:3px 7px;border-radius:99px;background:#f3f4f6;font-size:11px}.users-card .section-title{align-items:center}@media(max-width:850px){.user-row{grid-template-columns:1fr}.user-actions{justify-content:flex-start}}';document.head.appendChild(css);const timer=setInterval(addTab,800);window.addEventListener('beforeunload',()=>clearInterval(timer));window.ControlHorarioUsers={open,load};
})();
